services:
  mariadb:
    image: mariadb:11.2.2
    command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - "3316:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: aqoursql_dev
      MARIADB_PASSWORD: password123
      MARIADB_DATABASE: aqoursql
      TZ: "Asia/Tokyo"

  mariadb-test:
    image: mariadb:11.2.2
    command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - "3317:3306"
    volumes:
      - mariadb-test-data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: aqoursql_dev
      MARIADB_PASSWORD: password123
      MARIADB_DATABASE: aqoursql_test
      TZ: "Asia/Tokyo"

volumes:
  mariadb-data:
    driver: local
  mariadb-test-data:
    driver: local
