version: 2.1
jobs:
  build:
    working_directory: ~/clj-rest-api
    docker:
    - image: circleci/clojure:openjdk-11-lein-2.9.5
      environment:
        TZ: Asia/Tokyo
        TEST_DATABASE_URL: "jdbc:mysql://localhost:3306/aqoursql_test?user=aqoursql_dev&password=password123"
    - image: mariadb:10.5.8
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: aqoursql_dev
        MYSQL_PASSWORD: password123
        MYSQL_DATABASE: aqoursql_test
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          sudo apt-get update --allow-releaseinfo-change
          sudo apt-get install -y mariadb-client
    - run:
        name: Wait for DB startup
        command: |
          dockerize -wait tcp://localhost:3306 -timeout 1m
    - run:
        name: Import DDL
        command: |
          mysql -h127.0.0.1 -P3306 -uroot -proot aqoursql_test < sql/ddl/aqoursql.sql
    - restore_cache:
        key: clj-rest-api-{{ checksum "project.clj" }}
    - run: lein deps
    - run: lein test-coverage
    - run: lein lint
    - run:
        name: Install static code analysis tools
        environment:
          CLJSTYLE_VERSION: 0.14.0
          CLJ_KONDO_VERSION: 2020.12.12
          JOKER_VERSION: 0.15.7
        command: |
          # cljstyle
          wget https://github.com/greglook/cljstyle/releases/download/${CLJSTYLE_VERSION}/cljstyle_${CLJSTYLE_VERSION}_linux.tar.gz
          tar -xzf cljstyle_${CLJSTYLE_VERSION}_linux.tar.gz
          sudo mv -f cljstyle /usr/local/bin/
          # clj-kondo
          curl -sLO https://raw.githubusercontent.com/borkdude/clj-kondo/master/script/install-clj-kondo
          chmod +x install-clj-kondo
          sudo ./install-clj-kondo --version ${CLJ_KONDO_VERSION}
          # Joker
          wget https://github.com/candid82/joker/releases/download/v${JOKER_VERSION}/joker-${JOKER_VERSION}-linux-amd64.zip
          unzip -qq joker-${JOKER_VERSION}-linux-amd64.zip
          sudo mv -f joker /usr/local/bin/
    - run: make lint
    - run: bash <(curl -s https://codecov.io/bash) -f '!*.txt'
    - save_cache:
        key: clj-rest-api-{{ checksum "project.clj" }}
        paths:
        - ~/.lein
        - ~/.m2
    - run:
        name: Save test results
        command: |
          mkdir -p ~/test-results/clojure-test
          if [ -f target/coverage/junit.xml ]; then
            cp target/coverage/junit.xml ~/test-results/clojure-test/
          fi
        when: always
    - store_test_results:
        path: ~/test-results
