version: 2.1
jobs:
  build:
    working_directory: ~/clj-rest-api
    docker:
    - image: cimg/clojure:1.11.1-openjdk-17.0
      environment:
        TZ: Asia/Tokyo
        TEST_DATABASE_URL: "jdbc:mariadb://localhost:3306/aqoursql_test?user=aqoursql_dev&password=password123"
    - image: mariadb:11.2.2
      command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
      environment:
        MARIADB_ROOT_PASSWORD: root
        MARIADB_USER: aqoursql_dev
        MARIADB_PASSWORD: password123
        MARIADB_DATABASE: aqoursql_test
        TZ: Asia/Tokyo
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          sudo apt update --allow-releaseinfo-change
          sudo apt install -y mariadb-client
    - run:
        name: Wait for DB startup
        command: |
          dockerize -wait tcp://localhost:3306 -timeout 1m
    - run:
        name: Import DDL
        command: |
          mariadb -h127.0.0.1 -P3306 -uroot -proot aqoursql_test < sql/ddl/aqoursql.sql
    - restore_cache:
        key: clj-rest-api-{{ checksum "project.clj" }}
    - run: lein deps
    - run: lein test-coverage
    - run: lein lint
    - run:
        name: Install static code analysis tools
        environment:
          CLJSTYLE_VERSION: 0.16.626
          CLJ_KONDO_VERSION: 2023.12.15
          JOKER_VERSION: 1.3.4
        command: |
          # cljstyle
          wget https://github.com/greglook/cljstyle/releases/download/${CLJSTYLE_VERSION}/cljstyle_${CLJSTYLE_VERSION}_linux_amd64.zip
          unzip -qq cljstyle_${CLJSTYLE_VERSION}_linux_amd64.zip
          sudo mv -f cljstyle /usr/local/bin/
          # clj-kondo
          curl -sLO https://raw.githubusercontent.com/borkdude/clj-kondo/master/script/install-clj-kondo
          chmod +x install-clj-kondo
          sudo ./install-clj-kondo --version ${CLJ_KONDO_VERSION}
          # Joker
          wget https://github.com/candid82/joker/releases/download/v${JOKER_VERSION}/joker-linux-amd64.zip
          unzip -qq joker-linux-amd64.zip
          sudo mv -f joker /usr/local/bin/
    - run: make lint
    - run: bash <(curl -s https://codecov.io/bash) -f '!*.txt'
    - save_cache:
        key: clj-rest-api-{{ checksum "project.clj" }}
        paths:
        - ~/.lein
        - ~/.m2
    - run:
        name: Save test results
        command: |
          mkdir -p ~/test-results/clojure-test
          if [ -f target/coverage/junit.xml ]; then
            cp target/coverage/junit.xml ~/test-results/clojure-test/
          fi
        when: always
    - store_test_results:
        path: ~/test-results
